package net.baka4n.elementera.core.reg.common.item.reg;

import net.baka4n.elementera.Elementera;
import net.baka4n.elementera.core.reg.ItemReg;
import net.baka4n.elementera.core.reg.common.item.*;
import net.minecraft.item.Item;

import static net.baka4n.elementera.Elementera.modid;

public class RegI {
    public static final Protium protium = new Protium();
    public static final Deuterium deuterium = new Deuterium();
    public static final Tritium tritium = new Tritium();
    public static final Helium helium_2 = new Helium();
    public static final Helium helium_3 = new Helium();
    public static final Helium helium = new Helium();
    public static final Helium helium_5 = new Helium();
    public static final Helium helium_6 = new Helium();
    public static final Helium helium_7 = new Helium();
    public static final Helium helium_8 = new Helium();
    public static final Helium helium_9 = new Helium();
    public static final Helium helium_10 = new Helium();
    public static final Lithium lithium_6 = new Lithium();
    public static final Lithium lithium = new Lithium();
    public static final Beryllium beryllium_7 = new Beryllium();
    public static final Beryllium beryllium = new Beryllium();
    public static final Beryllium beryllium_9 = new Beryllium();
    public static final Beryllium beryllium_10 = new Beryllium();
    public static final Boron boron_6 = new Boron();
    public static final Boron boron_7 = new Boron();
    public static final Boron boron_8 = new Boron();
    public static final Boron boron_9 = new Boron();
    public static final Boron boron_10 = new Boron();
    public static final Boron boron_11 = new Boron();
    public static final Boron boron_12 = new Boron();
    public static final Boron boron_13 = new Boron();
    public static final Boron boron_14 = new Boron();
    public static final Boron boron_15 = new Boron();
    public static final Boron boron_16 = new Boron();
    public static final Boron boron_17 = new Boron();
    public static final Boron boron_18 = new Boron();
    public static final Boron boron_19 = new Boron();
    public static final Carbon carbon_8 = new Carbon();
    public static final Carbon carbon_9 = new Carbon();
    public static final Carbon carbon_10 = new Carbon();
    public static final Carbon carbon_11 = new Carbon();
    public static final Carbon carbon = new Carbon();
    public static final Carbon carbon_13 = new Carbon();
    public static final Carbon carbon_14 = new Carbon();
    public static final Carbon carbon_15 = new Carbon();
    public static final Carbon carbon_16 = new Carbon();
    public static final Carbon carbon_17 = new Carbon();
    public static final Carbon carbon_18 = new Carbon();
    public static final Carbon carbon_19 = new Carbon();
    public static final Carbon carbon_20 = new Carbon();
    public static final Carbon carbon_21 = new Carbon();
    public static final Carbon carbon_22 = new Carbon();
    public static final Nitrogen nitrogen_10 = new Nitrogen();
    public static final Nitrogen nitrogen_11 = new Nitrogen();
    public static final Nitrogen nitrogen_25 = new Nitrogen();
    public static final Oxygen oxygen = new Oxygen();

    public RegI() {
        regItem("protium", protium);
        regItem("deuterium", deuterium);
        regItem("tritium", tritium);
        regItem("helium_2", helium_2);
        regItem("helium_3", helium_3);
        regItem("helium", helium);
        regItem("helium_5", helium_5);
        regItem("helium_6", helium_6);
        regItem("helium_7", helium_7);
        regItem("helium_8", helium_8);
        regItem("helium_9", helium_9);
        regItem("helium_10", helium_10);
        regItem("lithium_6", lithium_6);
        regItem("lithium", lithium);
        regItem("beryllium_7", beryllium_7);
        regItem("beryllium", beryllium);
        regItem("beryllium_9", beryllium_9);
        regItem("beryllium_10", beryllium_10);
        regItem("Boron_6", boron_6);
        regItem("boron_7", boron_7);
        regItem("boron_8", boron_8);
        regItem("boron_9", boron_9);
        regItem("boron_10", boron_10);
        regItem("boron_11", boron_11);
        regItem("boron_12", boron_12);
        regItem("boron_13", boron_13);
        regItem("boron_14", boron_14);
        regItem("boron_15", boron_15);
        regItem("boron_16", boron_16);
        regItem("boron_17", boron_17);
        regItem("boron_18", boron_18);
        regItem("boron_19", boron_19);
        regItem("carbon_8", carbon_8);
        regItem("carbon_9", carbon_9);
        regItem("carbon_10", carbon_10);
        regItem("carbon_11", carbon_11);
        regItem("carbon", carbon);
        regItem("carbon_13", carbon_13);
        regItem("carbon_14", carbon_14);
        regItem("carbon_15", carbon_15);
        regItem("carbon_16", carbon_16);
        regItem("carbon_17", carbon_17);
        regItem("carbon_18", carbon_18);
        regItem("carbon_19", carbon_19);
        regItem("carbon_20", carbon_20);
        regItem("carbon_21", carbon_21);
        regItem("carbon_22", carbon_22);
        regItem("nitrogen_10", nitrogen_10);
        regItem("nitrogen_11", nitrogen_11);
        regItem("nitrogen_25", nitrogen_25);
        regItem("oxygen", oxygen);
    }

    private static void regItem(String itemN, Item item) {
        ItemReg.regItem(modid, itemN, item);
    }
}
